name: CI-CD
# MAKE SURE SETTINGS > ACTIONS > GENERAL HAS WORKFLOW PERMISSIONS ABLE TO EDIT

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: 'main'

            - name: Set up PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Compile build
              run: pnpm build

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              with: # More info about the arguments on the action page
                  author_name: Github Build Action
                  message: 'Commit CI build'
                  add: 'dist'
                  tag_push: '--force'
                  fetch: false
                  github_token: ${{ secrets.GITHUB_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
    publish:
        name: Publish to NPM
        runs-on: ubuntu-latest
        needs: build # This makes it wait for the build job
        steps:
            - name: Get build
              uses: actions/checkout@v4
              with:
                  ref: 'main'

            - name: Set up PNPM
              uses: pnpm/action-setup@v4
              with:
                  registry-url: https://registry.npmjs.org/ # Required in order to publish to npm
                  version: latest
            - name: Publish
              run: pnpm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
